name: 'Check for missing Due Dates'

on:
  schedule:
  - cron: '45 21 * * *'
    timezone: 'Europe/London'
jobs:
  reminder:
  # Runs-on is the runner, the ubuntu-latest is github hosted
    runs-on: ubuntu-latest
    steps:
      - name: Check for missing due dates and write a comment
        uses: petrandr/duedate_reminders@latest
        with:
          gh_token: ${{ secrets.DUE_DATE_TOKEN }}
          project_number: 2
          notify_for: "missing_duedate"
          duedate_field_name: "Due Date"
          notification_type: "comment"
